# Generated by Codex on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_payment_booking_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'created_at'], name='bookings_bo_booking_b42fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'booking_status'], name='bookings_bo_show_id_bdc770_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['screen', 'seat_number'], name='bookings_se_screen__02aa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['show', 'status', 'locked_until'], name='bookings_se_show_id_762e67_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['seat', 'show'], name='bookings_se_seat_id_390a36_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(condition=models.Q(status__in=['locked', 'booked']), fields=('seat', 'show'), name='unique_active_seat_reservation'),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('template_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='bookings_em_status_87ccab_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['booking', 'status'], name='bookings_em_booking_10e143_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='bookings_pa_provider_3c5a85_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['status', 'created_at'], name='bookings_pa_status_50ca22_idx'),
        ),
    ]
