# Generated by Django 6.0.2 on 2026-03-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_queue_and_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_booking_3b5ee7_idx',
            old_name='bookings_bo_booking_b42fe3_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_show_id_d07f76_idx',
            old_name='bookings_bo_show_id_bdc770_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='bookings_em_status_10042f_idx',
            old_name='bookings_em_status_87ccab_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='bookings_em_booking_814ad9_idx',
            old_name='bookings_em_booking_10e143_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhookevent',
            new_name='bookings_pa_provide_7f7993_idx',
            old_name='bookings_pa_provider_3c5a85_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhookevent',
            new_name='bookings_pa_status_064cd0_idx',
            old_name='bookings_pa_status_50ca22_idx',
        ),
        migrations.RenameIndex(
            model_name='seat',
            new_name='bookings_se_screen__7efa2c_idx',
            old_name='bookings_se_screen__02aa1d_idx',
        ),
        migrations.RenameIndex(
            model_name='seatreservation',
            new_name='bookings_se_show_id_21a10f_idx',
            old_name='bookings_se_show_id_762e67_idx',
        ),
        migrations.RenameIndex(
            model_name='seatreservation',
            new_name='bookings_se_seat_id_c15ef9_idx',
            old_name='bookings_se_seat_id_390a36_idx',
        ),
    ]
