# Generated by Django 6.0.2 on 2026-03-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'show_time'], name='movies_show_movie_i_489ba0_idx'),
        ),
    ]
