# Generated by Codex on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genre_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'language'], name='movies_mov_genre_24cdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'release_date'], name='movies_mov_genre_f8e31e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'release_date'], name='movies_mov_langua_95effb_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'rating'], name='movies_mov_genre_24955f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'rating'], name='movies_mov_langua_3f7a08_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['screen', 'show_time'], name='movies_show_screen__3dbffe_idx'),
        ),
    ]
