# Generated by Django 6.0.2 on 2026-03-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_movie_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_genre_08a05d_idx',
            old_name='movies_mov_genre_24cdaa_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_genre_544b59_idx',
            old_name='movies_mov_genre_f8e31e_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_languag_d0ac8c_idx',
            old_name='movies_mov_langua_95effb_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_genre_772261_idx',
            old_name='movies_mov_genre_24955f_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_languag_431ee3_idx',
            old_name='movies_mov_langua_3f7a08_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='movies_show_screen__780cf6_idx',
            old_name='movies_show_screen__3dbffe_idx',
        ),
    ]
